language: php
php:
    - 7.3
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
services:
    - redis-server
    - mongodb
    - mysql
before_install:
    - if [[ $DISABLE_XDEBUG == "true" ]]; then phpenv config-rm xdebug.ini; fi
    - sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'kooser'
    - mysql -e 'CREATE DATABASE test_db;'
install:
    - echo "extension = wincache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - travis_retry composer install --no-interaction
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
    - chmod +x php-coveralls.phar
    - php php-coveralls.phar --version
after_success:
    - travis_retry php php-coveralls.phar -v
before_script:
    - mkdir -p build/logs
    - ls -al
script:
    - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
    - ./vendor/bin/psalm
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
