language: php
php:
    - 7.3
cache:
    directories:
        - $HOME/.composer/cache
addons:
    apt:
        sources:
            - mysql-5.7-trusty
    packages:
        - mysql-server
        - mysql-client
env:
    - HANDLER=mysql
services:
    - mongodb
    - mysql
before_install:
    - if [[ $DISABLE_XDEBUG == "true" ]]; then phpenv config-rm xdebug.ini; fi
    - if [[ "$HANDLER" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test_db;" -uroot; fi
install:
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - travis_retry composer install --no-interaction
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
    - chmod +x php-coveralls.phar
    - php php-coveralls.phar --version
after_success:
    - travis_retry php php-coveralls.phar -v
before_script:
    - mkdir -p build/logs
    - ls -al
script:
    - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
    - ./vendor/bin/psalm
    - if [[ $STATIC_ANALYSIS != "" ]]; then composer check-cs; fi
    - if [[ $STATIC_ANALYSIS != "" ]]; then composer phpstan; fi
